# fly.toml app configuration file generated for hrdc-ims-staging on 2025-03-27T21:10:06-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hrdc-ims-staging'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "data"
  destination = "/data"

[env]
  INVENTORY_DB_PATH="/data/inventory.db"
  USERS_DB_PATH="/data/users.db"
